export enum RoutePaths {
  Index = '',
  Password = 'password',
  Auth = 'auth',
  LoginLanding = 'login-landing',
  LoginLandingWithMode = 'login-landing/:mode',
  Dashboard = 'dashboard',
  Activity = 'activity',
  Activities = 'activity/:instanceGuid',
  Home = 'home',
  TermsAndConditions = 'terms-and-conditions',
  PrivacyPolicy = 'privacy-policy',
  Survey = 'survey',
  // Activities
  Consent = 'consent',
  Demographics = 'demographics',
  GeneralMedicalBackgroundSurvey = 'general-medical-background',
  GeneralNeuroDevelopment = 'general-neuro-development',
  QualityOfLife = 'quality-of-life',
  ParentalConsent = 'parental-consent',
  ConsentAssent = 'consent-assent',
}
