export enum RoutePaths {
  Index = '',
  Password = 'password',
  Auth = 'auth',
  LoginLanding = 'login-landing',
  LoginLandingWithMode = 'login-landing/:mode',
  Dashboard = 'dashboard',
  ParticipantsList = 'participants',
  Activity = 'activity',
  Activities = 'activity/:instanceGuid',
  TermsAndConditions = 'terms-and-conditions',
  PrivacyPolicy = 'privacy-policy',
  Survey = 'survey',
  LoginRedirect = 'login-redirect',
}
