# To make our config generation "compatible" with official dsdetoolbox, extract what is needed from it (this is not the base image)
FROM broadinstitute/dsde-toolbox:consul-template-20-0.0.1 AS dsdetoolbox

FROM google/cloud-sdk:279.0.0

# Setting up Node
# Adapted from official Node Dockerfile https://github.com/nodejs/docker-node/blob/master/10/buster/Dockerfile
ENV NODE_VERSION 10.18.1

USER root

RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) ARCH='x64';; \
    ppc64el) ARCH='ppc64le';; \
    s390x) ARCH='s390x';; \
    arm64) ARCH='arm64';; \
    armhf) ARCH='armv7l';; \
    i386) ARCH='x86';; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac \
  # gpg keys listed at https://github.com/nodejs/node#release-keys
  && set -ex \
  && for key in \
    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    FD3A5288F042B6850C66B31F09FE44734EB7990E \
    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
    B9AE9905FFD7803F25714661B63B535A4C206CA9 \
    77984A986EBC2AA786BC0F66B01FBB92821C587A \
    8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600 \
    4ED778F539E3634C779C87C6D7062848A1AB005C \
    A48C2BEE680E841632CD4E44F07496B3EB3C1762 \
    B9E2F5981AA6E0CD28160D9FF13993A75599653C \
  ; do \
    gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$key" || \
    gpg --batch --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys "$key" || \
    gpg --batch --keyserver hkp://pgp.mit.edu:80 --recv-keys "$key" ; \
  done \
  && curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$ARCH.tar.xz" \
  && curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
  && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
  && grep " node-v$NODE_VERSION-linux-$ARCH.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
  && tar -xJf "node-v$NODE_VERSION-linux-$ARCH.tar.xz" -C /usr/local --strip-components=1 --no-same-owner \
  && rm "node-v$NODE_VERSION-linux-$ARCH.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt \
  && ln -s /usr/local/bin/node /usr/local/bin/nodejs

# Copying necessary artifacts to enable configure.rb that lives in our own repo.
COPY --from=dsdetoolbox /usr/local/bin/consul-template /usr/local/bin/consul-template
COPY --from=dsdetoolbox /etc/consul-template/config/config.json /etc/consul-template/config/config.json
COPY --from=dsdetoolbox /usr/local/bin/vault /usr/local/bin/vault
ENV VAULT_ADDR https://clotho.broadinstitute.org:8200


RUN apt-get update && apt-get install -y \
    ruby:amd64=1:2.5.1 \
    jq \
   && rm -rf /var/lib/apt/lists/*


# Setting up Angular CLI globally
ENV ANGULAR_CLI @angular/cli@8.3.23
RUN npm install --global $ANGULAR_CLI

# Create app directory
WORKDIR /usr/src/sheetappend
COPY ./sheetappend/*.js .
COPY ./sheetappend/package*.json ./
RUN npm install
RUN npm link

# keep track of git hash
ARG GIT_SHA
RUN echo $GIT_SHA > git_sha.txt

CMD "/bin/bash"
