export enum dashboardType {
  VERTICAL_HIGHLIGHTED_BAR_CHART = 'VERTICAL_HIGHLIGHTED_BAR_CHART',
  VERTICAL_BAR_CHART = 'VERTICAL_BAR_CHART',
  HORIZONTAL_BAR_CHART = 'HORIZONTAL_BAR_CHART',
  DONUT_CHART = 'DONUT_CHART',
  COUNT = 'COUNT'
}
