export enum StudyEnum {
  AT = 'AT',
  BRUGADA = 'Brugada',
  BASIL = 'basil',
  ANGIO = 'Angio',
  BRAIN = 'Brain',
  DARWIN = `Darwin's Ark`,
  OSTEO = 'Osteo',
  MBC = 'MBC',
  PROSTATE = 'Prostate',
  ESC = 'ESC',
  PANCAN = 'PanCan',
  PRION = 'Prion',
  VOICES = 'Voices',
  LMS = 'Leiomyosarcoma',
  OSTEO2 = 'OS PE-CGS',
  RGP = 'RGP',
  RAREX = 'RareX',
  SINGULAR = 'Singular',
  TEST_BOSTON = 'Test Boston'
}
