export const AppRoutes = {
    Activity: 'activity',
    ActivityId: 'activity/:id',
    ActivityLinkId: 'activity-link/:id',
    Error: 'error',
    Join: 'join',
    LoginLanding: 'login-landing',
    LoginLandingMode: 'login-landing/:mode',
    AdminLoginLanding: 'admin-login-landing',
    LocalAuth: 'auth',
    Consent: 'consent',
    CovidSurvey: 'covid-survey',
    Dashboard: 'dashboard',
    CrcDashboard: 'prism',
    Password: 'password',
    SessionExpired: 'session-expired',
    Privacy: 'privacy-policy',
    Address: 'mailing-address',
    PasswordResetDone: 'password-reset-done'
};
