export const AppRoutes = {
    Activity: 'activity',
    ActivityId: 'activity/:id',
    ActivityLinkId: 'activity-link/:id',
    Error: 'error',
    Join: 'join',
    LanguageRedirect: 'language-redirect',
    LoginLanding: 'login-landing',
    LoginLandingMode: 'login-landing/:mode',
    AdminLoginLanding: 'admin-login-landing',
    LocalAuth: 'auth',
    Consent: 'consent',
    CovidSurvey: 'covid-survey',
    Dashboard: 'dashboard',
    Prism: 'prism',
    Password: 'password',
    SessionExpired: 'session-expired',
    AdminSessionExpired: 'admin-session-expired',
    Address: 'mailing-address',
    PasswordResetDone: 'password-reset-done',
    EnrollSubject: 'enrollment'
};
