export enum ActivityCodes {
  Prequal = 'PREQUAL',
  SelfConsent = 'CONSENT',
  ParentalConsent = 'PARENTAL_CONSENT',
  ConsentAssent = 'CONSENT_ASSENT',
  LarConsent = 'LAR_CONSENT',
  LarConsentAssent = 'LAR_CONSENT_ASSENT',
  AddParticipant = 'ADD_PARTICIPANT',
  DataSharing = 'DATA_SHARING',
  GeneralInformation = 'GENERAL_INFORMATION',
  HealthAndDevelopment = 'HEALTH_AND_DEVELOPMENT',
  QualityOfLife = 'QUALITY_OF_LIFE',
  ChildQualityOfLife = 'CHILD_QUALITY_OF_LIFE',
  PatientQualityOfLife = 'PATIENT_QUALITY_OF_LIFE',
  LegacySurvey = 'LEGACY',
  FamilyMember = 'FAMILY_MEMBER',
}
