export enum Activities {
  PREQUAL = 'PREQUAL',
  LEGACY_SURVEY = 'LEGACY',
  CONSENT = 'CONSENT',
  ASSENT = 'ASSENT',
  PARENTAL_CONSENT = 'PARENTAL_CONSENT',
  CONSENT_ASSENT = 'CONSENT_ASSENT',
  MEDICAL_BACKGROUND_SURVEY = 'GENERAL_MEDICAL_BACKGROUND_SURVEY',
  NEURODEVELOPMENT_SURVEY = 'GENERAL_NEURODEVELOPMENT_SURVEY',
  QOL_SURVEY = 'GENERAL_QOL_SURVEY',
  DEMOGRAPHICS = 'DEMOGRAPHICS',
  DATA_FROM_EXISTING_SOURCES_AGREEMENT = 'DATA_FROM_EXISTING_SOURCES_AGREEMENT',
  MEDICAL_RECORDS_AGREEMENT = 'MEDICAL_RECORDS_AGREEMENT',
  BIOSAMPLES_AGREEMENT = 'BIOSAMPLES_AGREEMENT',
  DATA_SHARING_PREFERENCES_AGREEMENT = 'DATA_SHARING_PREFERENCES_AGREEMENT'
}
