export enum ActivityCodes {
  PREQUAL = 'PREQUAL',
  CONSENT = 'CONSENT',
  DEMOGRAPHICS = 'DEMOGRAPHICS',
  GENERAL_MEDICAL_BACKGROUND_SURVEY = 'GENERAL_MEDICAL_BACKGROUND_SURVEY',
  GENERAL_NEURO_DEVELOPMENT = 'GENERAL_NEURO_DEVELOPMENT',
  QUALITY_OF_LIFE = 'QUALITY_OF_LIFE'
}
