export enum ActivityCodes {
  PREQUAL = 'PREQUAL',
  CONSENT = 'CONSENT',
  PARENTAL_CONSENT = 'PARENTAL_CONSENT',
  CONSENT_ASSENT = 'CONSENT_ASSENT',
  FAMILY_MEMBER = 'FAMILY_MEMBER',
  DEMOGRAPHICS = 'DEMOGRAPHICS',
  GENERAL_MEDICAL_BACKGROUND_SURVEY = 'GENERAL_MEDICAL_BACKGROUND_SURVEY',
  GENERAL_NEURO_DEVELOPMENT = 'GENERAL_NEURO_DEVELOPMENT',
  QUALITY_OF_LIFE = 'QUALITY_OF_LIFE'
}
