export const AppRoutes = {
    Activity: 'activity',
    ActivityId: 'activity/:id',
    ActivityLinkId: 'activity-link/:id',
    Error: 'error',
    LoginLanding: 'login-landing',
    LoginLandingMode: 'login-landing/:mode',
    LocalAuth: 'auth',
    AboutYou: 'about-you',
    Consent: 'consent',
    Release: 'release-survey',
    Dashboard: 'dashboard',
    Password: 'password',
    SessionExpired: 'session-expired',
    PasswordResetDone: 'password-reset-done',
    CountMeIn: 'count-me-in',
    AboutUs: 'about-us',
    Data: 'data',
    MoreDetails: 'more-details',
    JoinList: 'join-list'
};
