version: 2.1
references:
  npm_cache_key: &npm_cache_key
                   v1-dependency-npm-{{ checksum "package-lock.json" }}
jobs:
  build:
    docker:
      - image: broadinstitute/pepper-angular-toolkit:build_v1
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Update interpolated ENV vars
          command: |
            echo 'export ANGULAR_PROJECT_NAME=ddp-$STUDY_KEY' >> $BASH_ENV
            echo 'export ANGULAR_PROJECT_DIR_PATH=projects/ddp-$STUDY_KEY' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Show pipeline vars
          command: |
            echo "pipeline.id << pipeline.id >>"
            echo "pipeline.number	 << pipeline.number	 >>"
            echo "pipeline.project.git_url << pipeline.project.git_url >>"
            echo "pipeline.project.type << pipeline.project.type >>"
            echo "pipeline.git.tag << pipeline.git.tag >>"
            echo "pipeline.git.branch << pipeline.git.branch >>"
            echo "pipeline.git.revision << pipeline.git.revision >>"
            echo "pipeline.git.base_revision << pipeline.git.base_revision >>"
      - run:
          name: Pick deployment environment
          command: |
            case "<< pipeline.git.branch >>" in
            	develop) DEPLOY_DEV=dev;;
            	appengine_deployment) DEPLOY_DEV=GAEHEREWEGO;;
            	staging) DEPLOY_DEV=staging;;
            	*) DEPLOY_DEV=NOTHING!;;
            esac
            echo "Setting deployment ENVIRONMENT to $DEPLOY_DEV"
            echo "export ENVIRONMENT=$DEPLOY_DEV" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Show ENV variables
          command: env
      - run:
          name: Generate config files
          command: ./build-study.sh v1 $ENVIRONMENT $STUDY_KEY $STUDY_GUID --config
          environment:
            USE_DOCKER: false
      - restore_cache:
          key: *npm_cache_key
      - run:
          name: npm install Angular workspace
          command: npm install
          working_directory: ~/repo/ddp-workspace
      - save_cache:
          key: *npm_cache_key
          paths:
            - ./node_modules
      - run:
          name: Angular Build
          command: ng build $ANGULAR_PROJECT_NAME --prod --aot --base-href=/ --output-path=$ANGULAR_PROJECT_DIR_PATH/dist --verbose=true --progress=true
          working_directory: ~/repo/ddp-workspace
      - run:
          name: Setup gcloud context
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: Deploy to GAE
          command: gcloud app deploy "${ANGULAR_PROJECT_DIR_PATH}/app.yaml"
          working_directory: ~/repo/ddp-workspace

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - appengine_deployment

