# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: broadinstitute/pepper-angular-toolkit:build_v1
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Update interpolated ENV vars
          command: |
            echo 'export ANGULAR_PROJECT_NAME=ddp-$STUDY_KEY' >> $BASH_ENV; source $BASH_ENV
            echo 'export ANGULAR_PROJECT_DIR_PATH=ddp-workspace/projects/$ANGULAR_PROJECT_NAME'; source $BASH_ENV
            echo 'export OUTPUT_DIR=$ANGULAR_PROJECT_DIR_PATH/output-config'; source $BASH_ENV
      - run:
          name: Show ENV variables
          command: env
      - run:
          name: Generating configuration files
          command: ruby configure.rb -y
          environment:
            INPUT_DIR: config
            MANIFEST: manifest-study.rb
            USE_DOCKER: false
      - run:
          name: Install Angular Project
          command: npm ci
          working_directory: ~/repo/ddp-workspace
      - run:
          name: Angular Build
          command: ng build $ANGULAR_PROJECT_NAME --base-href=/ --output-path=$ANGULAR_PROJECT_DIR_PATH/dist --verbose=true --progress=true
          working_directory: ~/repo/ddp-workspace
      - run:
          name: Setup gcloud context
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: Deploy to GAE
          command: gcloud app deploy "${ANGULAR_PROJECT_DIR_PATH}/app.yaml"



#  build:
#    docker:
#      - image: broadinstitute/pepper-angular-toolkit:build_v1
#
#    working_directory: ~/repo
#
#    steps:
#      - run: |
#          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
#          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
#          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
#
#      - checkout:
#            path: ~/repo
#
##      - run: npm ci
#
#      - run: echo "The project is $PROJ"
#
#      - run:  gcloud --quiet app describe

#      - run:  VERSION=v1 ENV=dev OUTPUT_DIR=ddp-workspace/projects/output-config INPUT_DIR=ddp-workspace/projects/$PROJ STUDY_KEY=osteo STUDY_GUID=CMI-OSTEO ruby configure.rb -y

#      - run: ng build $PROJ --base-href=/ --output-path=dist/$PROJ --verbose=true --progress=true

 #     - run: ls -l ./dist/ddp-osteo/output-config
