export enum UserPermission {
  DEATH_INDEX_DOWNLOAD = 'ndi_download',
  DOWNLOAD_PDFS = 'pdf_download',
  FIELD_SETTINGS_ADD_REMOVE_MODIFY = 'field_settings',
  FOLLOW_UP_SURVEYS = 'survey_creation',
  KIT_DISCARD_SAMPLES = 'discard_sample',
  KIT_VIEW_AND_DEACTIVATION_REACTIVATION = 'kit_deactivation',
  KIT_CREATE_OVERNIGHT_SHIPPING_LABELS = 'kit_express',
  KIT_RECEIVE_AND_SCAN = 'kit_receiving',
  KIT_CLINICAL_ORDER = 'kit_seqeuncing_order',
  KIT_SHIPPING = 'kit_shipping',
  KIT_VIEW_KIT_PAGES = 'kit_shipping_view',
  KIT_UPLOAD = 'kit_upload',
  KIT_UPLOAD_INVALID_ADDRESS = 'kit_upload_invalid_address',
  MAILING_LIST_VIEW_AND_DOWNLOAD = 'mailingList_view',
  MANAGE_STUDY_PERMISSIONS = 'study_user_admin',
  MEDICAL_RECORDS_ADD_TO_ABSTRACTOR_ASSIGNEE_LIST = 'mr_abstractor',
  MEDICAL_RECORDS_ABSTRACTION = 'mr_abstraction_admin',
  MEDICAL_RECORDS_CANNOT_REQUEST_TISSUE = 'mr_no_request_tissue',
  MEDICAL_RECORDS_QUALITY_ASSURANCE = 'mr_qc',
  MEDICAL_RECORDS_ADD_TO_REQUESTER_ASSIGNEE_LIST = 'mr_request',
  MEDICAL_RECORDS_VIEW_AND_REQUEST_RECORDS_AND_TISSUE = 'mr_view',
  PARTICIPANT_EDIT = 'participant_edit',
  PARTICIPANT_FILES_VIEW_DOWNLOAD = 'file_download',
  PARTICIPANT_STOP_AUTOMATED_EMAILS = 'participant_event',
  PARTICIPANT_WITHDRAWAL = 'participant_exit',
  PARTICIPANT_VIEW_LIST = 'pt_list_view',
  ONC_HISTORY_UPLOAD = 'upload_onc_history',
  SEQUENCING_ORDER_VIEW_STATUS = 'view_seq_order_status',
  SHARED_LEARNINGS_UPLOAD_FILE = 'upload_ror_file',
  SHARED_LEARNINGS_VIEW = 'view_shared_learnings',
  VIEW_SURVEY_DATA_ONLY = 'view_only_dss_data',
}

