import { Decalcification, GeneralAnswer, OncHistoryRequestStatus } from '../enums/oncHistory-enum'

export interface OncHistoryDetail {
    oncHistoryID?: number,
    requestOncHistoryDetail(): Promise<void>,
    accessTissueRequestPage(): Promise<void>,
    dateOfPX?: string,
    typeOfPX?: string,
    locationOfPX?: string,
    histology?: string,
    accessionNumber?: string,
    facility?: string,
    phone?: string,
    fax?: string,
    destructionPolicy?: string | number,
    localControl?: GeneralAnswer,
    decalcification?: Decalcification,
    ffpe?: GeneralAnswer,
    blocksWithTumor?: string,
    tumorSize?: string,
    blockToRequest?: string,
    necrosis?: string,
    viableTumor?: string,
    slidesToRequest?: string,
    facilityWhereSampleWasReviewed?: string,
    slidesTotal?: string,
    treatmentEffect?: string,
    setOncHistoryRequestStatus(status: OncHistoryRequestStatus): Promise<void>,
}
