dispatch:
  - url: "ascproject.org/*"
    service: angio
  - url: "mbcproject.org/*"
    service: mbc
  - url: "braincancerproject.org/*"
    service: brain
  - url: "osproject.org/*"
    service: osteo
  - url: "testboston.org/*"
    service: testboston
  - url: "mpcproject.org/*"
    service: mpc
  - url: "pepper-backend.prod.datadonationplatform.org/*"
    service: pepper-backend
  - url: "pepper.datadonationplatform.org/*"
    service: pepper-backend
  - url: "dsm.datadonationplatform.org/api/*"
    service: study-manager-backend
  - url: "dsm.datadonationplatform.org/*"
    service: study-manager-ui
