dispatch:
  - url: "ascproject.org/*"
    service: angio
  - url: "mbcproject.org/*"
    service: mbc
  - url: "braincancerproject.org/*"
    service: brain
  - url: "osproject.org/*"
    service: osteo
  - url: "testboston.org/*"
    service: testboston
  - url: "mpcproject.org/*"
    service: mpc
  - url: "prionregistry.org/*"
    service: prion
  - url: "pepper.datadonationplatform.org/docs*"
    service: pepper-api-spec
  - url: "pepper.datadonationplatform.org/spec/*"
    service: pepper-api-spec
  - url: "pepper.datadonationplatform.org/*"
    service: pepper-backend
  - url: "dsm.datadonationplatform.org/ddp/*"
    service: study-manager-backend
  - url: "dsm.datadonationplatform.org/api/*"
    service: study-manager-backend
  - url: "dsm.datadonationplatform.org/app/*"
    service: study-manager-backend
  - url: "dsm.datadonationplatform.org/info/*"
    service: study-manager-backend
  - url: "dsm.datadonationplatform.org/ui/*"
    service: study-manager-backend
  - url: "dsm.datadonationplatform.org/*"
    service: study-manager-ui
