export enum Route {
  Home = '',
  About = 'about',
  Team = 'team',
  FAQ = 'faq',
  Join = 'join',
  Registration = 'registration',
  Login = 'login',
  LoginLanding = 'login-landing',
  Error = 'error',
  Password = 'password',
  Auth = 'auth',
  PasswordReset = 'reset-password',
  SessionExpired = 'session-expired',
  Dashboard = 'dashboard',
  Activity = 'activity',
  ActivityId = 'activity/:id',
  LoginLandingMode = 'login-landing/:mode',
}
