export enum SequencingOrderEnum {
  SELECT = 1,
  SAMPLE_TYPE = 2,
  SAMPLE = 3,
  SAMPLE_STATUS = 4,
  COLLECTION_DATE = 5,
  LATEST_SEQUENCING_ORDER_DATE = 6,
  LATEST_ORDER_STAUS = 7,
  LATEST_ORDER_NUMBER = 8,
  LATEST_PDO_NUMBER = 9,
}