export enum Route {
  Home = '',
  FAQ = 'faq',
  Join = 'join',
  Auth = 'auth',
  About = 'about',
  Login = 'login',
  Error = 'error',
  Survey = 'survey/:id',
  Contacts = 'contacts',
  Password = 'password',
  Activity = 'activity',
  Dashboard = 'dashboard',
  ActivityId = 'activity/:id',
  LoginLanding = 'login-landing',
  PreScreening = 'pre-screening',
  StudyProgress = 'study-progress',
  LoginRedirect = 'login-redirect',
  ParticipantList = 'participants',
  ForResearchers = 'for-researchers',
  SessionExpired = 'session-expired',
  AcceptAgeUp = 'accept',
  VerifyAgeUp = 'verify',
}
