import { test, expect } from '@playwright/test';
import { setAuth0UserEmailVerified } from 'utils/api-utils';
import { APP } from 'data/constants';
import * as auth from 'authentication/auth-base';
import { generateEmailAlias } from 'utils/faker-utils';
import * as testutils from 'utils/test-utils';

const { AT_USER_EMAIL, AT_USER_PASSWORD } = process.env;

test('ATFamiles test statics', async ({ page }) => {
  await page.goto('https://atcp.test.datadonationplatform.org/');
  await page.getByLabel('Password *').click();
  await page.getByLabel('Password *').fill('broad_institute');
  await page.getByLabel('Password *').press('Enter');
  await page.getByRole('button', { name: 'SDK.LanguageSelector.LanguageSelection English' }).click();
  await page.getByRole('menuitem', { name: 'Française' }).click();
  await page.getByRole('heading', { name: 'Aidez-nous à mieux comprendre l’ataxie-télangiectasie (AT).' }).click();
  await page.getByRole('button', { name: 'SDK.LanguageSelector.LanguageSelection Française' }).click();
  await page.getByRole('menuitem', { name: 'Türk' }).click();
  await page.getByRole('heading', { name: 'Sizde veya çocuğunuzda A-T varsa araştırmacıların yeni keşifler yapmaları ve tedavilerin gelişmesini hızlandırmalarına yardımcı olabilirsiniz. Her hastanın genetik bilgisi ve tıbbi durumu benzersizdir ve tedavilerin geliştirilmesine temel teşkil edebilir. Bu bilgiyi paylaşın, genom sekanslamamız için bize bir tükürük örneği gönderin ve A-T hakkında daha fazla bilgi edinme yolculuğumuzda bize katılın. Bize Katılın' }).click();
  await page.getByText('SDK.LanguageSelector.LanguageSelection Türk arrow_drop_down Araştırmacı Veri Eri').click();
  await page.getByRole('button', { name: 'SDK.LanguageSelector.LanguageSelection Türk' }).click();
  await page.getByRole('menuitem', { name: 'English' }).click();
  await page.getByRole('link', { name: 'For Researchers' }).click();
  await page.getByRole('link', { name: 'Data Access Request' }).click();
  await page.getByText('Our Data Access Committee (DAC) will review the DAR form submitted by the resear').click();
  await page.getByRole('link', { name: 'For Researchers' }).click();
  await page.getByRole('button', { name: 'Learn More' }).click();
  await page.getByRole('link', { name: 'About Us' }).click();
  await page.getByText('The Global A-T Family Data Platform is a patient-driven effort overseen by A-T f').click();
  await page.getByText('Our platform’s mission is to enable researchers to access important patient data').click();
  await page.getByText('In addition to ensuring that the platform’s activities promote and enable data s').click();
  await page.getByRole('heading', { name: 'Data Access Committee' }).click();
  await page.getByText('The information on the Global A-T Family Data Platform can only be accessed by q').click();
  await page.getByRole('button', { name: 'Learn More' }).click();
  await page.getByRole('link', { name: 'About this Initiative' }).click();
  await page.getByText('Ataxia-telangiectasia (A-T) is an inherited, neurodegenerative disease. A child ').click();
  await page.getByText('We recently identified several people who have typical, disease-causing mutation').click();

});


test('Test Signup', async ({ page }) => {
  await page.goto('http://atcp.test.datadonationplatform.org/');
  await page.getByLabel('Password *').click();
  await page.getByLabel('Password *').fill('broad_institute');
  await page.getByLabel('Password *').press('Enter');
  await page.locator('#join-us-nav').click();
  await page.waitForTimeout(1000);
  await testutils.findTextInput(page,'answer:PREQUAL_FIRST_NAME').fill('TestLast');
  await testutils.findTextInput(page,'answer:PREQUAL_LAST_NAME').fill('TestFirst');
  //await page.locator('.mat-form-field-infix').first().click();
  //await page.locator('#mat-input-1').fill('Andrew');
  //await page.locator('#mat-input-1').press('Tab');
  //await page.locator('#mat-input-2').fill('ZimmerPlaywright');
  await page.getByText('I\'m a parent/legal guardian of someone who has A-T.').click();
  await page.getByRole('button', { name: 'Join Us' }).click();
  await page.locator('#sign-up #email').click();

  const userEmail = generateEmailAlias(AT_USER_EMAIL);

  await page.locator('#sign-up #email').fill(userEmail);
  await page.locator('#sign-up #email').press('Tab');
  await page.locator('#sign-up #password').fill(AT_USER_PASSWORD!);
  await page.locator('#sign-up #password_confirm').fill(AT_USER_PASSWORD!);
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByText('Account Activation').click();
  await setAuth0UserEmailVerified(APP.AT, userEmail, { isEmailVerified: true });


  await page.locator('header').locator('a', { hasText: 'Sign In' }).click();
  //await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('#login #email').click();
  await page.locator('#login #email').fill(userEmail!);
  await page.getByRole('textbox', { name: 'Password Password (8 characters minimum)' }).click();
  await page.getByRole('textbox', { name: 'Password Password (8 characters minimum)' }).fill(AT_USER_PASSWORD!);
  await page.getByRole('button', { name: 'Sign In' }).click();

  await page.getByText('Signed in successfully.').click();

  await page.getByRole('button', { name: 'Add a Participant' }).click();
  await page.getByRole('heading', { name: 'New Participant\'s Enrollment Process' }).click();
  await page.getByText('Registration').click();
  await page.getByLabel('Participant\'s First Name*').click();
  await page.getByRole('combobox', { name: 'Participant\'s First Name*' }).fill('Andrew');
  await page.getByRole('combobox', { name: 'Participant\'s Last Name*' }).fill('Zimmer');
  await page.getByRole('combobox', { name: 'Participant\'s Prefix/Suffix (optional)' }).fill('Sir');
  await page.locator('#mat-input-4').selectOption('M');
  await page.locator('#mat-input-4').selectOption('F');
  await page.getByLabel('Choose a date').click();
  await page.getByRole('button', { name: 'Open calendar' }).click();
  await page.getByRole('button', { name: 'Choose month and year' }).click();
  await page.getByRole('button', { name: 'Previous 24 years' }).click();
  await page.getByText('1993').click();
  await page.getByText('JUN').click();
  await page.getByRole('gridcell', { name: 'June 2, 1993' }).getByText('2').click();
  await page.getByLabel('Participant\'s Street Address*').click();
  await page.getByRole('combobox', { name: 'Participant\'s Street Address*' }).fill('75 Ames St.');
  await page.getByLabel('Participant\'s City*').click();
  await page.getByRole('combobox', { name: 'Participant\'s City*' }).fill('Cambridge');
  await page.getByRole('combobox', { name: 'Participant\'s City*' }).press('Tab');
  await page.getByRole('combobox', { name: 'Participant\'s Postal Code*' }).fill('02420');
  // wait for country selection to drive state/province
  const requestPromise = page.waitForResponse(response => response.url().includes('https://pepper-test.datadonationplatform.org/pepper/v1/user') && response.status() === 200);
  await page.locator('#mat-input-10').selectOption('US');
  // await page.locator('#mat-input-10').click();
  const request = await requestPromise;
  
  
  await page.getByText("Participant's State/Province *");
  // why is this so slow?
  await page.locator('#mat-input-11').waitFor({timeout: 20 * 1000});

  await expect(page.getByRole('main').locator('div').filter({ hasText: '$' })).toHaveCount(0);
  await page.locator('#mat-input-11').selectOption('US-MA');

  await page.getByRole('button', { name: 'Register' }).click();
  await page.locator('.mat-checkbox-inner-container').click();
  await page.locator('.mat-checkbox-inner-container').click();
  await page.getByText('You must confirm that this participant was diagnosed with ataxia-telangiectasia ').click();
  await page.locator('label').filter({ hasText: 'I have been diagnosed with ataxia-telangiectasia' }).click();
  await page.getByRole('button', { name: 'Register' }).click();
  await page.locator('span').filter({ hasText: 'Consent' }).click();
  await page.getByText('Research Consent Form – Key Points "The Global A-T Family Data Platform" initiat').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download Complete Consent Form' }).click();
  const download = await downloadPromise;
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('1. What is the purpose of this research initiative?').click();
  await page.getByText('2. What will I have to do if I agree to participate in this effort?').click();
  await page.getByText('No. Taking part in any portion of this initiative is voluntary. If you decline t').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Prev' }).click();
  await page.getByText('We (the sponsors) want to better understand genetic and other biological and lif').click();
  await page.getByText('2. What will I have to do if I agree to participate in this effort?').click();
  await page.getByText('If you agree, you will periodically participate in additional research studies a').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('4. Will I benefit from participating?').click();
  await page.getByText('Participating in this study is unlikely to directly or immediately improve your ').click();
  await page.getByText('5. What are the risks of taking part in this research initiative?').click();
  await page.getByText('There is a potential risk that your information (which includes information from').click();
  await page.getByText('Filling out the questionnaires could lead you to feel uncomfortable or upset in ').click();
  await page.getByText('6. Will it cost me anything to participate in this research initiative?').click();
  await page.getByText('No.').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('9. What if I have questions?').click();
  await page.getByText('If you have any questions, concerns, or complaints please send an email to suppo').dblclick();
  await page.getByText('8. Can I stop taking part in this research initiative?').click();
  await page.getByText('Yes, you can withdraw from this research study at any time, and your data will n').click();
  await page.getByText('7. Who will use my samples and see my information?').click();
  await page.getByText('After removing your name and other readily identifiable information (this identi').click();
  await page.getByRole('button', { name: 'Prev' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('heading', { name: 'Consent' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('We encourage you to download and read the complete consent form carefully.').click();
  await page.getByText('Please contact us if you have any questions: support@atfamilies.org or +1 954-48').click();
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'arrow_circle_down Download Complete Consent Form' }).click();
  const download1 = await download1Promise;
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Prev' }).click();
  await page.getByText('We encourage you to download and read the complete consent form carefully.').click();
  await page.getByText('Please contact us if you have any questions: support@atfamilies.org or +1 954-48').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('This is what I agree to:').click();
  await page.getByText('Researchers may use my health information, medical information, the results of t').click();
  await page.getByText('Researchers may share this information with qualified researchers in a manner th').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('Check the boxes below to indicate if you agree to the following options. If you ').click();
  await page.getByText('Study staff may re-contact me with follow-up research questionnaires and invitat').click();
  await page.locator('.mat-radio-outer-circle').first().click();
  await page.locator('#mat-radio-3 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click();
  await page.locator('.mat-radio-outer-circle').first().click();
  await page.locator('#mat-radio-6 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click();
  await page.locator('#mat-radio-5 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('Please choose yes or no').first().click();
  await page.locator('#mat-radio-8 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click();
  await page.locator('#mat-radio-11 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click();
  await page.locator('#mat-radio-15 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click();
  await page.locator('#mat-radio-14 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('My signature below indicates:').click();
  await page.getByText('I have had enough time to read the consent form and think about agreeing to part').click();
  await page.getByText('I have had all of my questions answered to my satisfaction.').click();
  await page.getByText('I am willing to participate (or to allow my child to participate) in this resear').click();
  await page.getByText('I have been told that my or my child’s participation is voluntary and if I decid').click();
  await page.getByText('I have been told that if I decide to participate now (or allow my child to parti').click();
  await page.getByText('I agree to allow the collection, use, and sharing of my or my child’s informatio').click();
  await page.getByText('By signing this form, I do not give up any of my or my child’s legal rights.').click();
  await page.getByText('You should print a copy of this document for your records.').click();
  await page.getByText('I am a Parent or Legal Guardian of:').click();
  await page.locator('div').filter({ hasText: 'Participant Full Name' }).nth(2).click();
  await page.getByRole('combobox', { name: 'Participant Full Name' }).fill('Andrew Zimmer');
  await page.getByRole('combobox', { name: 'Participant Full Name' }).press('Tab');
  await page.locator('div').filter({ hasText: 'Participant Full Name' }).nth(2).click();
  await page.getByLabel('e.g. Mother').click();
  await page.getByRole('combobox', { name: 'e.g. Mother' }).click();
  await page.getByRole('combobox', { name: 'e.g. Mother' }).fill('Father');
  await page.getByLabel('Type signature here').click();
  await page.getByRole('combobox', { name: 'Type signature here' }).fill('Andrew Zimmer\'s Dad');
  await page.getByLabel('Choose a date').click();
  await page.getByLabel('Choose a date').fill('01/01/1950');
  await page.getByRole('button', { name: 'Sign & Consent' }).click();
  await page.locator('span').filter({ hasText: 'Contacting Physician' }).click();
  await page.getByRole('heading', { name: 'Contacting Physician' }).click();
  await page.getByRole('heading', { name: 'Our staff may contact Andrew\'s doctor with information about Andrew\'s data (if you so consented) or to confirm the A-T diagnosis. To enable that, please complete the following form with Andrew\'s physician\'s information (the doctor who plays the most central role in Andrew\'s care.' }).click();
  await page.getByLabel('Physician\'s First Name (optional)').click();
  await page.getByRole('combobox', { name: 'Physician\'s First Name (optional)' }).press('Tab');
  await page.getByRole('combobox', { name: 'Physician\'s Last Name*' }).fill('Dr. Jones');
  await page.getByRole('combobox', { name: 'Physician\'s Last Name*' }).press('Tab');
  await page.getByRole('combobox', { name: 'Physician\'s Complete Mailing Address*' }).fill('1234 Indiana Jones Road');
  await page.locator('div:nth-child(5) > .ddp-single-question > div > ddp-activity-question > .ddp-activity-question > ddp-activity-answer > ddp-activity-text-answer > ddp-activity-text-input > .activity-text-input > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click();
  await page.getByRole('combobox', { name: 'Physician\'s Phone*' }).fill('5555551212');
  await page.getByLabel('Physician\'s Email (optional)').click();
  await page.getByRole('combobox', { name: 'Physician\'s Email (optional)' }).click();
  await page.getByText('Andrew has been evaluated at (if applicable):').click();
  await page.locator('.mat-checkbox-inner-container').first().click();
  await page.locator('#mat-checkbox-6 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  await page.getByRole('button', { name: 'Save & Submit' }).click();
  // here
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await page.getByText('This module will ask you questions specific to your ataxia-telangiectasia (A-T) ').click();
  await page.getByText('If you have any questions, please contact us at +1 954-481-6611 - support@atfami').click();
  await page.getByRole('button', { name: 'Start/Resume' }).click();
  await page.locator('#mat-radio-18').click(); // click no
  await page.locator('#mat-radio-17').click(); // click yes
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Prev' }).click();
  await page.getByText('Has Andrew been diagnosed with Ataxia-Telangiectasia (A-T)?').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Years', { exact: true }).click();
  await page.getByLabel('Years', { exact: true }).fill('10');
  await page.locator('#mat-input-27').click();
  await page.locator('#mat-input-27').fill('5');
  await page.locator('#mat-input-28').click();
  await page.locator('#mat-input-28').fill('4');
  await page.getByText('Genetic Laboratory Analysis / Analysis of the ATM gene').click();
  await page.locator('#mat-checkbox-29 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#mat-input-29').click();
  await page.locator('#mat-input-29').fill('DUNK2');
  await page.getByLabel('Name of Physician:').click();
  await page.getByRole('combobox', { name: 'Name of Physician:' }).fill('Dr. Teeth');
  await page.getByRole('combobox', { name: 'Name of Physician:' }).press('Tab');
  await page.getByRole('combobox', { name: 'Physician Telephone Number:' }).fill('5555551212');
  await page.getByLabel('Hospital/Institution:').click();
  await page.getByRole('combobox', { name: 'Hospital/Institution:' }).fill('Muppets Memorial');
  await page.getByRole('combobox', { name: 'Hospital/Institution:' }).press('Tab');
  await page.getByRole('combobox', { name: 'City/Town/Village:' }).fill('Sesame St.');
  await page.getByRole('combobox', { name: 'City/Town/Village:' }).press('Tab');
  await page.getByRole('combobox', { name: 'State/Province/Region:' }).click();
  await page.getByRole('combobox', { name: 'State/Province/Region:' }).fill('Ohio');
  await page.locator('div').filter({ hasText: 'Country:' }).nth(2).click();
  await page.getByRole('combobox', { name: 'Country:' }).click();
  await page.getByRole('combobox', { name: 'Country:' }).fill('Muppet');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('Yes').click();
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('At what age was Andrew diagnosed with cancer?').click();
  await page.getByText('Please select the type of cancer:').click();
  await page.getByText('Please indicate the status of Andrew\'s condition:').click();
  await page.locator('div').filter({ hasText: 'Years old' }).nth(2).click();
  await page.getByLabel('Years old').fill('5');
  await page.locator('label').filter({ hasText: 'Non-Hodgkin\'s Lymphoma' }).click();
  await page.locator('#mat-radio-29 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await page.getByText('Ambulation').click();
  await page.locator('.mat-radio-outer-circle').first().click();
  await page.getByText('If Andrew is no longer fully ambulatory, at what age did Andrew begin using a wh').click();
  await page.getByText('If Andrew is no longer fully ambulatory, at what age did Andrew depend completel').click();
  await page.locator('li:nth-child(3) > ddp-activity-question > .ddp-activity-question > ddp-activity-answer > ddp-activity-text-answer > ddp-activity-text-input > .activity-text-input > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click();
  await page.locator('#mat-input-38').fill('5');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await page.getByText('Symptoms or conditions associated with A-T').click();
  await page.locator('.mat-checkbox-inner-container').first().click();
  await page.locator('#mat-checkbox-38 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  await page.locator('#mat-checkbox-45 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  await page.locator('#mat-checkbox-49 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  await page.locator('#mat-checkbox-52').click();
  await page.getByText('Frequent infections - lung').click();
  await page.getByText('Frequent infections - sinus').click();
  await page.locator('#mat-checkbox-54 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  await page.locator('#mat-checkbox-57 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await page.getByText('Other symptoms or conditions').click();
  await page.locator('#mat-checkbox-61 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  await page.locator('#mat-checkbox-67 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  await page.locator('#mat-checkbox-72 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  await page.getByLabel('Please specify:').click();
  await page.getByLabel('Please specify:').fill('Another symptom');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await page.getByText('No').nth(0).click();
  await page.getByText('Yes').nth(0).click();
  await page.getByText('At what age did Andrew experience the onset of her period?').click();
  // answer:FEMALE_AGE_OF_ONSET_PERIOD
  await page.locator('#mat-input-41').click();
  await page.locator('#mat-input-41').fill('9');
  await page.getByText('Yes').nth(1).click();
  await page.getByText('No').nth(1).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await page.getByText('Has Andrew ever had any of the following infectious diseases? Select all that ap').click();
  await page.getByText('Measles').click();
  await page.locator('#mat-checkbox-77 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  await page.getByText('No', { exact: true }).click();
  await page.locator('.mat-radio-outer-circle').first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await page.getByText('Please specify the type of immunodeficiency (select all that apply):').click();
  await page.locator('#mat-radio-54').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await page.getByText('Has Andrew ever acquired an infection from an immunization?').click();
  await page.locator('#mat-radio-59 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click();
  await page.getByText('Surgeries (Select all that apply):').click();
  await page.locator('#mat-checkbox-83 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  await page.getByLabel('Andrew\'s age at time of surgery:').click();
  await page.getByLabel('Andrew\'s age at time of surgery:').fill('5');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await page.getByText('Medications: Has Andrew ever taken any medications in the following categories?(').click();
  await page.locator('#mat-input-43').selectOption('ANTI_DEPRESSANT');
  await page.locator('#mat-input-43').selectOption('ANTI_DROOLING');
  await page.locator('#mat-input-43').selectOption('PROPHYLACTIC_ANTIBIOTICS');
  await page.locator('#mat-input-43').selectOption('STEROID');
  await page.getByLabel('Medication name').click();
  await page.getByRole('combobox', { name: 'Medication name' }).fill('Steroid 123');
  await page.locator('div').filter({ hasText: 'Began taking at age' }).nth(2).click();
  await page.getByRole('combobox', { name: 'Began taking at age' }).click();
  await page.getByRole('combobox', { name: 'Began taking at age' }).fill('6');
  await page.locator('ddp-activity-composite-answer div').filter({ hasText: 'Medication category Prophylactic antibiotics Anti-tremor Anti-seizure Anti-drool' }).click();
  await page.getByRole('button', { name: '+ Add Another Medication' }).click();
  await page.locator('#mat-input-46').selectOption('DIABETES');
  await page.locator('#mat-input-47').click();
  await page.locator('#mat-input-47').fill('Diabetes med 1');
  await page.locator('div:nth-child(4) > ddp-activity-answer:nth-child(3) > ddp-activity-text-answer > ddp-activity-text-input > .activity-text-input > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click();
  await page.locator('#mat-input-48').fill('10');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await page.getByText('Does Andrew currently take any over-the-counter nutritional supplements?').click();
  await page.locator('#mat-radio-63').getByText('No').click();
  await page.getByText('Are Andrew\'s parents consanguineous (closely related, for example: first cousins').click();
  await page.locator('#mat-radio-67 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click();
  await page.locator('#mat-input-49').selectOption('DROPDOWN_MALE');
  await page.locator('#mat-input-49').selectOption('DROPDOWN_FEMALE');
  await page.getByLabel('Age', { exact: true }).click();
  await page.getByRole('combobox', { name: 'Age', exact: true }).fill('20');
  await page.locator('ddp-date div').filter({ hasText: 'Date of Birth' }).nth(4).click();
  await page.getByLabel('Date of Birth').fill('10/10/1982');
  await page.locator('#mat-input-53').selectOption('DIAGNOSIS_DROPDOWN_UNKNOWN');
  await page.locator('#mat-input-53').selectOption('DIAGNOSIS_DROPDOWN_YES');
  await page.locator('#mat-input-53').selectOption('DIAGNOSIS_DROPDOWN_NO');
  await page.locator('#mat-input-54').selectOption('CARRIER_DROPDOWN_NO');
  await page.locator('#mat-input-54').selectOption('CARRIER_DROPDOWN_UNKNOWN');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await page.getByText('Has Andrew previously participated in any clinical drug trials related to A-T?').click();
  await page.locator('#mat-radio-71 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click();
  await page.getByText('currently participate').click();
  await page.getByText('Does Andrew currently participate in any clinical drug trials related to A-T?').click();
  await page.locator('#mat-radio-75 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click();
  await page.getByText('Has Andrew previously donated a sample of blood, tissue, or other biospecimen fo').click();
  await page.locator('#mat-radio-78 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await page.getByText('Samples: : Please enter the type and location (if known) of any donated samples ').click();
  await page.locator('#mat-input-55').selectOption('URINE');
  await page.locator('#mat-input-55').selectOption('BLOOD');
  await page.locator('#mat-input-55').selectOption('OTHER_BODILY_FLUID');
  await page.locator('#mat-input-55').selectOption('BLOOD');
  await page.getByLabel('Location (if known)').click();
  await page.getByRole('combobox', { name: 'Location (if known)' }).click();
  await page.getByRole('combobox', { name: 'Location (if known)' }).fill('Muppetville Hospital');
  await page.getByRole('button', { name: '+ Add Another Biospecimen' }).click();
  await page.locator('#mat-input-57').selectOption('URINE');
  await page.locator('#mat-input-58').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('.activity-header')).toHaveText('Medical History');
  await page.getByText('You\'re almost done! Please click "Submit" at the bottom to complete this form.').click();
  await page.getByText('Your responses have been saved, but not submitted. You can leave and come back a').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('heading', { name: 'Genome Study' }).click();
  await page.getByText('If you wish to participate in the whole genome sequencing study, we will send yo').click();
  await page.getByText('We recommend that you provide the saliva collection in the presence of a healthc').click();
  await page.locator('.mat-checkbox-inner-container').click();
  await page.locator('.mat-checkbox-inner-container').click();
  await page.locator('.mat-checkbox-inner-container').click();
  await page.locator('#mat-input-61').selectOption('FINNISH');
  await page.locator('#mat-input-61').selectOption('AFRICAN_AFRICAN_AMERICAN');
  await page.getByRole('button', { name: 'Save & Submit' }).click();
  await page.getByRole('heading', { name: 'Review & Submission' }).click();
  await page.getByRole('heading', { name: 'Please review the information you provided during this enrollment process and submit when you have confirmed that it is correct.' }).click();
  await page.getByRole('heading', { name: 'We look forward to learning about your experiences with A-T.' }).click();
  await page.getByRole('button', { name: 'Save & Submit Enrollment' }).click();
  await page.getByRole('heading', { name: 'Thank you for joining the Global A-T Family Data Platform!' }).click();
  await page.getByRole('heading', { name: 'Family members who have A-T' }).click();
  await page.getByText('Andrew Zimmer').click();
  await page.getByText('Submitted Enrollment / Pending Confirmation').click();
  await page.getByRole('button', { name: 'Expand' }).click();
  await page.getByRole('cell', { name: 'Registration', exact: true }).click();
  await page.getByRole('cell', { name: 'Consent', exact: true }).click();
  await page.getByRole('cell', { name: 'Contacting Physician', exact: true }).click();
  await page.getByRole('cell', { name: 'Medical History', exact: true }).click();
  await page.getByRole('cell', { name: 'Genome Study', exact: true }).click();
  await page.getByRole('cell', { name: 'Review & Submission' }).first().click();
  await page.getByRole('row', { name: 'Registration Thank you for signing the registration form.' }).getByRole('cell', { name: 'Complete' }).click();
  await page.getByRole('row', { name: 'Consent Thank you for signing the research consent form.' }).getByRole('cell', { name: 'Complete' }).click();
  await page.getByRole('row', { name: 'Contacting Physician Thank you for signing the contacting physician form.' }).getByRole('cell', { name: 'Complete' }).click();
  await page.getByRole('row', { name: 'Medical History Thank you for signing the Medical History form.' }).getByRole('cell', { name: 'Complete' }).click();
  await page.getByRole('row', { name: 'Genome Study Thank you for signing the Genome Study form.' }).getByRole('cell', { name: 'Complete' }).click();
  await page.getByRole('row', { name: 'Review & Submission Review & Submission' }).getByRole('cell', { name: 'Complete' }).click();
  await page.getByRole('row', { name: 'Registration Thank you for signing the registration form.' }).getByRole('button', { name: 'View' }).click();
  await page.getByRole('heading', { name: 'Andrew\'s Enrollment Process' }).click();
  await page.getByRole('heading', { name: 'Registration' }).click();
  await page.getByRole('button', { name: 'My Account' }).click();
  await page.getByRole('link', { name: 'Your Participants' }).click();
  await page.getByRole('heading', { name: 'Thank you for joining the Global A-T Family Data Platform!' }).click();
  await page.getByRole('heading', { name: 'Family members who have A-T' }).click();
  await page.getByText('Andrew Zimmer').click();
  await page.getByRole('button', { name: 'Expand' }).click();

});
