
dispatch:
  - url: "pepper-dev.datadonationplatform.org/docs*"
    service: pepper-api-spec
  - url: "pepper-dev.datadonationplatform.org/spec/*"
    service: pepper-api-spec
  - url: "angio.dev.datadonationplatform.org/*"
    service: angio
  - url: "mbc.dev.datadonationplatform.org/*"
    service: mbc
  - url: "brain.dev.datadonationplatform.org/*"
    service: brain
  - url: "osteo.dev.datadonationplatform.org/*"
    service: osteo
  - url: "testboston.dev.datadonationplatform.org/*"
    service: testboston
  - url: "pepper-backend.dev.datadonationplatform.org/*"
    service: pepper-backend
  - url: "pepper-dev.datadonationplatform.org/*"
    service: pepper-backend
