dispatch:
  - url: "angio.dev.datadonationplatform.org/*"
    service: angio
  - url: "mbc.dev.datadonationplatform.org/*"
    service: mbc
  - url: "brain.dev.datadonationplatform.org/*"
    service: brain
  - url: "osteo.dev.datadonationplatform.org/*"
    service: osteo
  - url: "rare-x.dev.datadonationplatform.org/*"
    service: rarex
  - url: "testboston.dev.datadonationplatform.org/*"
    service: testboston
  - url: "mpc.dev.datadonationplatform.org/*"
    service: mpc
  - url: "esc.dev.datadonationplatform.org/*"
    service: esc
  - url: "prion.dev.datadonationplatform.org/*"
    service: prion
  - url: "pepper-dev.datadonationplatform.org/docs*"
    service: pepper-api-spec
  - url: "pepper-dev.datadonationplatform.org/spec/*"
    service: pepper-api-spec
  - url: "pepper-dev.datadonationplatform.org/*"
    service: pepper-backend
  - url: "dsm-dev.datadonationplatform.org/ddp/*"
    service: study-manager-backend
  - url: "dsm-dev.datadonationplatform.org/api/*"
    service: study-manager-backend
  - url: "dsm-dev.datadonationplatform.org/app/*"
    service: study-manager-backend
  - url: "dsm-dev.datadonationplatform.org/info/*"
    service: study-manager-backend
  - url: "dsm-dev.datadonationplatform.org/ui/*"
    service: study-manager-backend
  - url: "dsm-dev.datadonationplatform.org/*"
    service: study-manager-ui
