dispatch:
  - url: "angio.staging.datadonationplatform.org/*"
    service: angio
  - url: "mbc.staging.datadonationplatform.org/*"
    service: mbc
  - url: "brain.staging.datadonationplatform.org/*"
    service: brain
  - url: "osteo.staging.datadonationplatform.org/*"
    service: osteo
  - url: "testboston.staging.datadonationplatform.org/*"
    service: testboston
  - url: "pepper-backend.staging.datadonationplatform.org/*"
    service: pepper-backend
  - url: "pepper-staging.datadonationplatform.org/*"
    service: pepper-backend
  - url: "dsm.staging.datadonationplatform.org/api/*"
    service: study-manager-backend
  - url: "dsm.staging.datadonationplatform.org/*"
    service: study-manager-ui
