dispatch:
  - url: "angio.staging.datadonationplatform.org/*"
    service: angio
  - url: "mbc.staging.datadonationplatform.org/*"
    service: mbc
  - url: "brain.staging.datadonationplatform.org/*"
    service: brain
  - url: "osteo.staging.datadonationplatform.org/*"
    service: osteo
  - url: "testboston.staging.datadonationplatform.org/*"
    service: testboston
  - url: "mpc.staging.datadonationplatform.org/*"
    service: mpc
  - url: "esc.staging.datadonationplatform.org/*"
    service: esc
  - url: "prion.staging.datadonationplatform.org/*"
    service: prion
  - url: "pepper-staging.datadonationplatform.org/docs*"
    service: pepper-api-spec
  - url: "pepper-staging.datadonationplatform.org/spec/*"
    service: pepper-api-spec
  - url: "pepper-staging.datadonationplatform.org/*"
    service: pepper-backend
  - url: "dsm-staging.datadonationplatform.org/ddp/*"
    service: study-manager-backend
  - url: "dsm-staging.datadonationplatform.org/api/*"
    service: study-manager-backend
  - url: "dsm-staging.datadonationplatform.org/app/*"
    service: study-manager-backend
  - url: "dsm-staging.datadonationplatform.org/info/*"
    service: study-manager-backend
  - url: "dsm-staging.datadonationplatform.org/ui/*"
    service: study-manager-backend
  - url: "dsm-staging.datadonationplatform.org/*"
    service: study-manager-ui
