export enum ActivityCodes {
  PREQUALIFIER = "PREQUAL",
  REGISTRATION = "REGISTRATION",
  CONSENT = "CONSENT",
  ASSENT = "ASSENT",
  CONTACTING_PHYSICIAN =  "CONTACTING_PHYSICIAN",
  MEDICAL_HISTORY = "MEDICAL_HISTORY",
  GENOME_STUDY = "GENOME_STUDY",
  REVIEW_AND_SUBMISSION = "REVIEW_AND_SUBMISSION",
}
